### ISSUE TITLE
npm run dashboard-test fail

### ISSUE THREAD

**Issue by 108kb** [orcinustools/orcinus#44]
When I execute `npm run dashboard-test`, test didn't start because problem in connection via mongoose.

![2018-09-21_22-57-56](https://user-images.githubusercontent.com/6561394/45892292-e74ab100-bdf1-11e8-9f2e-6df059fa6b67.png)

But when I add prefix with `mongodb://` in `db/index.js`, it works well. Should we add it?

![2018-09-21_23-01-31](https://user-images.githubusercontent.com/6561394/45892420-4e686580-bdf2-11e8-94eb-fce204046017.png)

**Comment by filosofikode** [comment]
hmm

https://github.com/orcinustools/orcinus/blob/master/deploy/dashboard/orcinus.yml#L14
